/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.12.2.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as addPlayer from "../addPlayer";
import type * as createGame from "../createGame";
import type * as getGame from "../getGame";
import type * as listGames from "../listGames";
import type * as listMessages from "../listMessages";
import type * as listPlayers from "../listPlayers";
import type * as sendMessage from "../sendMessage";
import type * as updateGameStatus from "../updateGameStatus";
import type * as updatePlayerState from "../updatePlayerState";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  addPlayer: typeof addPlayer;
  createGame: typeof createGame;
  getGame: typeof getGame;
  listGames: typeof listGames;
  listMessages: typeof listMessages;
  listPlayers: typeof listPlayers;
  sendMessage: typeof sendMessage;
  updateGameStatus: typeof updateGameStatus;
  updatePlayerState: typeof updatePlayerState;
}>;
