/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.12.2.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as changeDirection from "../changeDirection";
import type * as createLobby from "../createLobby";
import type * as getCurrentLobby from "../getCurrentLobby";
import type * as getGameState from "../getGameState";
import type * as getPlayerByClientID from "../getPlayerByClientID";
import type * as joinLobby from "../joinLobby";
import type * as leaveLobby from "../leaveLobby";
import type * as listLobbies from "../listLobbies";
import type * as listLobbyMembers from "../listLobbyMembers";
import type * as setPlayerName from "../setPlayerName";
import type * as startGame from "../startGame";
import type * as tickGame from "../tickGame";
import type * as updateGameStatus from "../updateGameStatus";
import type * as updatePlayerState from "../updatePlayerState";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  changeDirection: typeof changeDirection;
  createLobby: typeof createLobby;
  getCurrentLobby: typeof getCurrentLobby;
  getGameState: typeof getGameState;
  getPlayerByClientID: typeof getPlayerByClientID;
  joinLobby: typeof joinLobby;
  leaveLobby: typeof leaveLobby;
  listLobbies: typeof listLobbies;
  listLobbyMembers: typeof listLobbyMembers;
  setPlayerName: typeof setPlayerName;
  startGame: typeof startGame;
  tickGame: typeof tickGame;
  updateGameStatus: typeof updateGameStatus;
  updatePlayerState: typeof updatePlayerState;
}>;
